CREATE TABLE PATIENTS ( 
PatientID INT PRIMARY KEY, 
Name VARCHAR(100) NOT NULL, 
Phone VARCHAR(20), 
DateOfBirth DATE NOT NULL 
); 

CREATE TABLE DENTISTS ( 
DentistID INT PRIMARY KEY, 
Name VARCHAR(100) NOT NULL, 
Specialization VARCHAR(50) 
); 

CREATE TABLE APPOINTMENTS ( 
AppID INT PRIMARY KEY, 
PatientID INT, 
DentistID INT, 
Date DATE NOT NULL, 
Status VARCHAR(20) CHECK (Status IN ('Scheduled', 'Completed', 'Cancelled')), 
FOREIGN KEY (PatientID) REFERENCES PATIENTS(PatientID), 
FOREIGN KEY (DentistID) REFERENCES DENTISTS(DentistID) 
); 

CREATE TABLE TREATMENTS ( 
TreatmentID INT PRIMARY KEY, 
ServiceName VARCHAR(100) NOT NULL, 
Price DECIMAL(10, 2) CHECK (Price > 0) 
); 

CREATE TABLE INVENTORY ( 
ItemID INT PRIMARY KEY, 
ItemName VARCHAR(100) NOT NULL, 
StockLevel INT DEFAULT 0 
); 

CREATE TABLE TREATMENT_DETAILS ( 
DetailID INT PRIMARY KEY, 
AppID INT, 
TreatmentID INT, 
ItemID INT, 
ToothNumber INT, 
QuantityUsed INT DEFAULT 1, 
FOREIGN KEY (AppID) REFERENCES APPOINTMENTS(AppID), 
FOREIGN KEY (TreatmentID) REFERENCES TREATMENTS(TreatmentID), 
FOREIGN KEY (ItemID) REFERENCES INVENTORY(ItemID) 
); 

CREATE TABLE INVOICES ( 
InvoiceID INT PRIMARY KEY, 
AppID INT UNIQUE, 
TotalAmount DECIMAL(10, 2) DEFAULT 0, 
IssuedDate DATE NOT NULL, 
FOREIGN KEY (AppID) REFERENCES APPOINTMENTS(AppID) 
); 

CREATE TABLE PAYMENTS ( 
PaymentID INT PRIMARY KEY, 
InvoiceID INT, 
Amount DECIMAL(10, 2) NOT NULL, 
Method VARCHAR(20) CHECK (Method IN ('Cash', 'Card', 'Transfer')), 
FOREIGN KEY (InvoiceID) REFERENCES INVOICES(InvoiceID) 
); 

 
• CREATE INDEX idx_patient_name ON PATIENTS(Name); 

• CREATE INDEX idx_appointment_date ON APPOINTMENTS(Date); 

• CREATE INDEX idx_invoice_app ON INVOICES(AppID); 
